spring.application.name=desafio-petrobras-backend
spring.datasource.url=jdbc:mysql://localhost:3306/desafio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Recife
spring.datasource.username=root
spring.datasource.password=desafiomirante
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
